version: '2'
services:
    jhipsterbotfuel-app:
        image: jhipsterbotfuel
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jhipsterbotfuel-postgresql:5432/jhipsterBotfuel
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipsterbotfuel-postgresql:
        extends:
            file: postgresql.yml
            service: jhipsterbotfuel-postgresql
